class RealEstateItemModel {
  String id;
  String propertySubject;
  String propertyType;
  String propertyTypeLabel;
  String operationType;
  String operationTypeLabel;
  String advertiserRole;
  String advertiserRoleLabel;
  String saleType;
  String saleTypeLabel;
  String keywords;
  String propertyOwnerId;
  String propertyOwnerIdLabel;
  String lat;
  String lng;
  String propertyDetailedAddress;
  String price;
  String areaSqm;
  String commissionPercentage;
  String usageType;
  String usageTypeLabel;
  String propertyDescription;
  String featureIds;
  String facilityIds;
  String visitDays;
  String visitTimeFrom;
  String visitTimeTo;
  String propertyImages;
  String propertyVideos;
  String deedDocument;

  RealEstateItemModel({
    required this.id,
    required this.propertySubject,
    required this.propertyType,
    required this.propertyTypeLabel,
    required this.operationType,
    required this.operationTypeLabel,
    required this.advertiserRole,
    required this.advertiserRoleLabel,
    required this.saleType,
    required this.saleTypeLabel,
    required this.keywords,
    required this.propertyOwnerId,
    required this.propertyOwnerIdLabel,
    required this.lat,
    required this.lng,
    required this.propertyDetailedAddress,
    required this.price,
    required this.areaSqm,
    required this.commissionPercentage,
    required this.usageType,
    required this.usageTypeLabel,
    required this.propertyDescription,
    required this.featureIds,
    required this.facilityIds,
    required this.visitDays,
    required this.visitTimeFrom,
    required this.visitTimeTo,
    required this.propertyImages,
    required this.propertyVideos,
    required this.deedDocument,
  });
}
